# Generated by Django 4.2.4 on 2023-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("overview", models.TextField()),
                ("release_date", models.DateField()),
                ("poster_url", models.URLField()),
            ],
        ),
    ]
