# Generated by Django 4.2.4 on 2023-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="api_id",
            field=models.IntegerField(default=-1),
        ),
    ]
